### PR TITLE
解决编译时提示grpc及x/net安装不上怎么解决

### PR DESCRIPTION
**Pull request by bopo**
替换了GitHub源，国内可以编译通过

### CODE REVIEW

**Comment by bopo** [comment]
travis ci 的错误我看不到，不知道冲突在哪里

**Comment by bopo** [comment]
我只在go.mod 文件尾加了以下一段：

replace (
	cloud.google.com/go => github.com/googleapis/google-cloud-go v0.26.0
	golang.org/x/lint => github.com/golang/lint v0.0.0-20180702182130-06c8688daad7
	golang.org/x/net => github.com/golang/net v0.0.0-20181011144130-49bb7cea24b1
	golang.org/x/oauth2 => github.com/golang/oauth2 v0.0.0-20180821212333-d2e6202438be
	golang.org/x/sync => github.com/golang/sync v0.0.0-20180314180146-1d60e4601c6f
	golang.org/x/sys => github.com/golang/sys v0.0.0-20180830151530-49385e6e1522
	golang.org/x/text => github.com/golang/text v0.3.0
	golang.org/x/tools => github.com/golang/tools v0.0.0-20180828015842-6cd1fcedba52
	google.golang.org/appengine => github.com/golang/appengine v1.1.0
	google.golang.org/genproto => github.com/google/go-genproto v0.0.0-20180817151627-c66870c02cf8
	google.golang.org/grpc => github.com/grpc/grpc-go v1.16.0
)

**Comment by bopo** [comment]
实在不行的话，您就手动加到go.mod文件吧

**Comment by tonyboxes** [comment]
go: github.com/golang/lint@v0.0.0-20180702182130-06c8688daad7 used for two different module paths (github.com/golang/lint and golang.org/x/lint)

**Comment by tonyboxes** [comment]
试了下，golint版本有问题，我先修到develop中

**Pull request closed without merging**
